name = "discord-oidc"
main = "src/workers.ts"
compatibility_date = "2023-08-01"

kv_namespaces = [
  { binding = "KV", id = "4ad3b1178fb849e1a4c2b431bcda6678", preview_id = "e23db1fceb7646069ec79c5e72b0666f" }
]

[triggers]
crons = ["0 */1 * * *"]

[vars]
DISCORD_CLIENT_ID="1286283350717370378"
REDIRECT_URL="https://wakttu.cloudflareaccess.com/cdn-cgi/access/callback"
SERVERS_ROLE_CLAIMS=[
  "1224288512627707924",
  "1249662854140006540"
]
CACHE_ROLES=true
